### ISSUE TITLE
Error: Cannot store new snapshot value on CircleCI

### ISSUE THREAD

**Issue by kbariotis** [bahmutov/snap-shot-it#361]
## Is this a bug report or a feature request?
This is a bug report.

Using version `6.3.5`, I am getting this error only when running on CircleCI.

```
Error: Cannot store new snapshot value
in "/home/circleci/repo/test/e2e/interfaces/lambda/oauth/oauth.test.js"
for snapshot called "OAuth it should respond with initial HTML if shop exists"
test key "OAuth it should respond with initial HTML if shop exists 1"
when running on CI (opts.ci = 1)
see https://github.com/bahmutov/snap-shot-core/issues/5
    at throwCannotSaveOnCI (node_modules/snap-shot-it/node_modules/snap-shot-core/src/index.js:169:9)
    at setOrCheckValue (node_modules/snap-shot-it/node_modules/snap-shot-core/src/index.js:271:16)
    at core (node_modules/snap-shot-it/node_modules/snap-shot-core/src/index.js:308:12)
    at snapshot (node_modules/snap-shot-it/src/index.js:145:10)
    at Context.it (test/___/___/___/___.test.js:68:5)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

The `CI` env variable is set to true and tried the `SNAPSHOT_CI` and being mentioned in the [issue](https://github.com/bahmutov/snap-shot-core/issues/5).

Thank you

**Comment by bahmutov** [comment]
This is expected behavior - you should be able to update or save new snapshot values only when running locally. On CI you cannot inspect the value being saved, so trying to save new value means something is wrong. Most often this is because you have a snapshot in code, but forgot to commit the corresponding test.
