### ISSUE TITLE
Overriding "it" does not work watch mode :(

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot-it#8]
Trying to have watch mode and changing a test to fail breaks everything

```text
  1 passing (10ms)
  1 failing

  1) a-spec works:
     TypeError: Cannot read property 'test' of undefined
      at src/index.js:48:23
      at Context.<anonymous> (src/index.js:56:20)
```

**Comment by bahmutov** [comment]
Version `1.3.3` has been published to NPM. The full release note can be found at [snap-shot-it/releases/tag/v1.3.3](https://github.com/bahmutov/snap-shot-it/releases/tag/v1.3.3).

**Tip:** safely upgrade dependency snap-shot-it in your project using [next-update](https://github.com/bahmutov/next-update)
